merchx/merchx/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    path('email-sent/', views.email_sent, name='email-sent'),
    path('contact-us/', views.contact, name='contact'),
    path('listings/', views.listings, name="listing-list"),
    path('listings/add/', views.listing_create, name="listing-create"),
    path('listings/<int:listing_id>/',
         views.listing_detail, name='listing-detail'),
    path('listings/<int:listing_id>/update/',
         views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete/',
         views.listing_delete, name='listing-delete'),
]

merchx/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):

    class Types(models.TextChoices):
        RECORDS = 'disques'
        CLOTHING = 'vêtements'
        POSTERS = 'affiches'
        MISCELLANEOUS = 'divers'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=200)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)], blank=True)
    types = models.fields.CharField(choices=Types.choices, max_length=15)

    def __str__(self):
        return f'{self.title}'

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchx/listings/forms.py
from django import forms
from listings.models import Band
from listings.models import Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchx/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html', {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html', {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {'form': form})


def listings(request):
    announces = Listing.objects.all()
    return render(request,
                  'listings/listings.html', {'listings': announces})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            listing = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre a jour l'annonce et la sauvegarder dans la db
            form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                  'listings/listing_update.html',
                  {'form': form})


def listing_delete(request, listing_id):
    # nécessaire pour GET et pour POST
    listing = Listing.objects.get(id=listing_id)

    if request.method == 'POST':
        # supprimer l'annonce de la base de données
        listing.delete()
        # rediriger vers la liste des annonces
        return redirect('listing-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement
    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})


def listing_detail(request, listing_id):
    announce = Listing.objects.get(id=listing_id)
    return render(request,
                  'listings/listing_detail.html', {'listing': announce})


def about(request):
    return render(request, 'listings/about.html')


def contact(request):

    # ...nous pouvons supprimer les déclarations de journalisation qui étaient ici...

    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us from',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
        # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
        # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()

    return render(request, 'listings/contact.html', {'form': form})


def email_sent(request):
    return render(request, 'listings/email_sent.html')

merchx/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Page de About-us!</h1>

{% endblock %}

merchx/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchx/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}

merchx/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno|upper }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-update' band.id %}">Mettre à jour ce groupe</a>

<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>




{% for listing in band.listing_set.all %}
<!-- ajouter des liens vers toutes les annonces d'un groupe à partir de la page détaillée du groupe.
     Pour parcourir en boucle les annonces d'un groupe dans le gabarit -->
<a href="{% url 'listing-detail' listing.id %}">{{ listing.name }}</a>


{% endfor %}

{% endblock %}

merchx/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[Modifier]</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

merchx/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchx/listings/templates/listings/base.html
{% load static %}

<html>

<head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
</head>

<body>

    <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'listing-list' %}">Listings</a>
        <a href="{% url 'about' %}">À propos de nous</a>
        <a href="{% url 'contact' %}">Contact-nous</a>
    </nav>

    {% block content %}{% endblock %}

</body>

</html>

merchx/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content%}

<h1>Page de contact !</h1>

<h1>Nous sommes là pour vous aider</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchx/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<p>Votre enregistrment est un succès!!</p>

{% endblock %}

merchx/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer une nouvelle annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchx/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ listing.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}

merchx/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>{{ listing.title }}</h1>

<p>Mes annonces favorites sont :</p>

<ul>
    {% if listing.description %}
    <li>{{ listing.description }}</li>
    {% endif %}

    {% if listing.type %}
    <li>{{ listing.type }}</li>
    {% endif %}

    <li>{{ listing.sold|yesno|upper }}</li>

    {% if listing.year %}
    <li>{{ listing.year }}</li>
    {% endif %}

    {% if listing.band %}
    <li>{{ listing.band }}</li>
    {% endif %}
    <!-- <li>{{ listing.band }}</li> -->
</ul>

<a href="{% url 'listing-update' listing.id %}">Mettre a jour cette annonce</a>
<a href="{% url 'listing-delete' listing.id %}">Supprimer cette annonce</a>
<a href="{% url 'listing-list' %}">Retour à toutes les annonces</a>

{% endblock %}

merchx/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour d'une annonce</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchx/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Page des annonces!</h1>

<a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>

<p>
    Mes annonces favorites sont :
<ul>
    {% for listing in listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id%}">{{ listing.title }}</a>
        <a href="{% url 'listing-update' listing.id%}">[Modifier]</a>
    </li>
    {% endfor %}
</ul>
</p>

{% endblock %}